import { type NextPage } from "next";
import Head from "next/head";

import Navbar from "~/components/Navbar";

import Invoice from "~/components/Invoice/Invoice";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Invoice App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col bg-secondaryBlack">
        <Invoice />
      </main>
    </>
  );
};

export default Home;
